### ISSUE TITLE
HTMLView doesn't compile on fresh Ubuntu 16.04

### ISSUE THREAD

**Issue by cambiata** [haxeui/hxWidgets#36]
WebView.cpp:(.text+0x7a1): undefined reference to `wxWebViewBackendDefault'
WebView.cpp:(.text+0x8a3): undefined reference to `wxWebView::New(wxString const&)'
WebView.cpp:(.text+0xa64): undefined reference to `wxWebViewNameStr'
Error: error running g++ -o Main -rdynamic -m64 @obj/linux64/all_objs -lpthread -ldl -lwx_gtk2u_gl-3.0 -L/usr/lib/x86_64-linux-gnu -pthread -lwx_gtk2u_xrc-3.0 -lwx_gtk2u_html-3.0 -lwx_gtk2u_qa-3.0 -lwx_gtk2u_adv-3.0 -lwx_gtk2u_core-3.0 -lwx_baseu_xml-3.0 -lwx_baseu_net-3.0 -lwx_baseu-3.0 -ldl
Error: Build failed

**Comment by ianharrigan** [comment]
Yeah, getting the same issue on travis CI... will investigate it when i have time...

**Comment by ianharrigan** [comment]
Actually, its not the same issue, but either way, ill have to look into linux WebView

**Comment by cambiata** [comment]
Solved by updating to the latest git version and by running the following:
> sudo apt-get install libwxgtk-webview3.0-dev
Now webview works as expected! You rock, guys!
